# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'googlefblogin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for googlefblogin

  pod 'FBSDKCoreKit', '~> 4.40.0'
  pod 'FBSDKLoginKit', '~> 4.40.0'
  pod 'FBSDKShareKit', '~> 4.40.0'
  pod 'GoogleSignIn'
  pod 'Firebase/Core'

end


